#!/bin/bash

sh ./google-font-download "Roboto:100" "Roboto:100italic" "Roboto:300" "Roboto:300italic" "Roboto" "Roboto:italic" "Roboto:500" "Roboto:500italic" "Roboto:700" "Roboto:700italic" "Roboto:900" "Roboto:900italic" -oRoboto.css;
sh ./google-font-download "Open Sans:300" "Open Sans:300italic" "Open Sans" "Open Sans:italic" "Open Sans:600" "Open Sans:600italic" "Open Sans:700" "Open Sans:700italic" "Open Sans:800" "Open Sans:800italic" -oOpen_Sans.css;
sh ./google-font-download "Lato:100" "Lato:100italic" "Lato:300" "Lato:300italic" "Lato" "Lato:italic" "Lato:700" "Lato:700italic" "Lato:900" "Lato:900italic" -oLato.css;
sh ./google-font-download "Slabo 27px" -oSlabo_27px.css;
sh ./google-font-download "Oswald:200" "Oswald:300" "Oswald" "Oswald:500" "Oswald:600" "Oswald:700" -oOswald.css;
sh ./google-font-download "Roboto Condensed:300" "Roboto Condensed:300italic" "Roboto Condensed" "Roboto Condensed:italic" "Roboto Condensed:700" "Roboto Condensed:700italic" -oRoboto_Condensed.css;
sh ./google-font-download "Source Sans Pro:200" "Source Sans Pro:200italic" "Source Sans Pro:300" "Source Sans Pro:300italic" "Source Sans Pro" "Source Sans Pro:italic" "Source Sans Pro:600" "Source Sans Pro:600italic" "Source Sans Pro:700" "Source Sans Pro:700italic" "Source Sans Pro:900" "Source Sans Pro:900italic" -oSource_Sans_Pro.css;
sh ./google-font-download "Montserrat:100" "Montserrat:100italic" "Montserrat:200" "Montserrat:200italic" "Montserrat:300" "Montserrat:300italic" "Montserrat" "Montserrat:italic" "Montserrat:500" "Montserrat:500italic" "Montserrat:600" "Montserrat:600italic" "Montserrat:700" "Montserrat:700italic" "Montserrat:800" "Montserrat:800italic" "Montserrat:900" "Montserrat:900italic" -oMontserrat.css;
sh ./google-font-download "Raleway:100" "Raleway:100italic" "Raleway:200" "Raleway:200italic" "Raleway:300" "Raleway:300italic" "Raleway" "Raleway:italic" "Raleway:500" "Raleway:500italic" "Raleway:600" "Raleway:600italic" "Raleway:700" "Raleway:700italic" "Raleway:800" "Raleway:800italic" "Raleway:900" "Raleway:900italic" -oRaleway.css;
sh ./google-font-download "PT Sans" "PT Sans:italic" "PT Sans:700" "PT Sans:700italic" -oPT_Sans.css;
sh ./google-font-download "Merriweather:300" "Merriweather:300italic" "Merriweather" "Merriweather:italic" "Merriweather:700" "Merriweather:700italic" "Merriweather:900" "Merriweather:900italic" -oMerriweather.css;
sh ./google-font-download "Roboto Slab:100" "Roboto Slab:300" "Roboto Slab" "Roboto Slab:700" -oRoboto_Slab.css;
sh ./google-font-download "Open Sans Condensed:300" "Open Sans Condensed:300italic" "Open Sans Condensed:700" -oOpen_Sans_Condensed.css;
sh ./google-font-download "Lora" "Lora:italic" "Lora:700" "Lora:700italic" -oLora.css;
sh ./google-font-download "Droid Sans" "Droid Sans:700" -oDroid_Sans.css;
sh ./google-font-download "Ubuntu:300" "Ubuntu:300italic" "Ubuntu" "Ubuntu:italic" "Ubuntu:500" "Ubuntu:500italic" "Ubuntu:700" "Ubuntu:700italic" -oUbuntu.css;
sh ./google-font-download "Droid Serif" "Droid Serif:italic" "Droid Serif:700" "Droid Serif:700italic" -oDroid_Serif.css;
sh ./google-font-download "Playfair Display" "Playfair Display:italic" "Playfair Display:700" "Playfair Display:700italic" "Playfair Display:900" "Playfair Display:900italic" -oPlayfair_Display.css;
sh ./google-font-download "Noto Sans" "Noto Sans:italic" "Noto Sans:700" "Noto Sans:700italic" -oNoto_Sans.css;
sh ./google-font-download "Arimo" "Arimo:italic" "Arimo:700" "Arimo:700italic" -oArimo.css;
sh ./google-font-download "PT Serif" "PT Serif:italic" "PT Serif:700" "PT Serif:700italic" -oPT_Serif.css;
sh ./google-font-download "Titillium Web:200" "Titillium Web:200italic" "Titillium Web:300" "Titillium Web:300italic" "Titillium Web" "Titillium Web:italic" "Titillium Web:600" "Titillium Web:600italic" "Titillium Web:700" "Titillium Web:700italic" "Titillium Web:900" -oTitillium_Web.css;
sh ./google-font-download "PT Sans Narrow" "PT Sans Narrow:700" -oPT_Sans_Narrow.css;
sh ./google-font-download "Muli:200" "Muli:200italic" "Muli:300" "Muli:300italic" "Muli" "Muli:italic" "Muli:600" "Muli:600italic" "Muli:700" "Muli:700italic" "Muli:800" "Muli:800italic" "Muli:900" "Muli:900italic" -oMuli.css;
sh ./google-font-download "Poppins:300" "Poppins" "Poppins:500" "Poppins:600" "Poppins:700" -oPoppins.css;
sh ./google-font-download "Indie Flower" -oIndie_Flower.css;
sh ./google-font-download "Bitter" "Bitter:italic" "Bitter:700" -oBitter.css;
sh ./google-font-download "Dosis:200" "Dosis:300" "Dosis" "Dosis:500" "Dosis:600" "Dosis:700" "Dosis:800" -oDosis.css;
sh ./google-font-download "Inconsolata" "Inconsolata:700" -oInconsolata.css;
sh ./google-font-download "Oxygen:300" "Oxygen" "Oxygen:700" -oOxygen.css;
sh ./google-font-download "Hind:300" "Hind" "Hind:500" "Hind:600" "Hind:700" -oHind.css;
sh ./google-font-download "Fjalla One" -oFjalla_One.css;
sh ./google-font-download "Anton" -oAnton.css;
sh ./google-font-download "Noto Serif" "Noto Serif:italic" "Noto Serif:700" "Noto Serif:700italic" -oNoto_Serif.css;
sh ./google-font-download "Cabin" "Cabin:italic" "Cabin:500" "Cabin:500italic" "Cabin:600" "Cabin:600italic" "Cabin:700" "Cabin:700italic" -oCabin.css;
sh ./google-font-download "Arvo" "Arvo:italic" "Arvo:700" "Arvo:700italic" -oArvo.css;
sh ./google-font-download "Crimson Text" "Crimson Text:italic" "Crimson Text:600" "Crimson Text:600italic" "Crimson Text:700" "Crimson Text:700italic" -oCrimson_Text.css;
sh ./google-font-download "Libre Baskerville" "Libre Baskerville:italic" "Libre Baskerville:700" -oLibre_Baskerville.css;
sh ./google-font-download "Lobster" -oLobster.css;
sh ./google-font-download "Nunito:200" "Nunito:200italic" "Nunito:300" "Nunito:300italic" "Nunito" "Nunito:italic" "Nunito:600" "Nunito:600italic" "Nunito:700" "Nunito:700italic" "Nunito:800" "Nunito:800italic" "Nunito:900" "Nunito:900italic" -oNunito.css;
sh ./google-font-download "Yanone Kaffeesatz:200" "Yanone Kaffeesatz:300" "Yanone Kaffeesatz" "Yanone Kaffeesatz:700" -oYanone_Kaffeesatz.css;
sh ./google-font-download "Catamaran:100" "Catamaran:200" "Catamaran:300" "Catamaran" "Catamaran:500" "Catamaran:600" "Catamaran:700" "Catamaran:800" "Catamaran:900" -oCatamaran.css;
sh ./google-font-download "Josefin Sans:100" "Josefin Sans:100italic" "Josefin Sans:300" "Josefin Sans:300italic" "Josefin Sans" "Josefin Sans:italic" "Josefin Sans:600" "Josefin Sans:600italic" "Josefin Sans:700" "Josefin Sans:700italic" -oJosefin_Sans.css;
sh ./google-font-download "Bree Serif" -oBree_Serif.css;
sh ./google-font-download "Roboto Mono:100" "Roboto Mono:100italic" "Roboto Mono:300" "Roboto Mono:300italic" "Roboto Mono" "Roboto Mono:italic" "Roboto Mono:500" "Roboto Mono:500italic" "Roboto Mono:700" "Roboto Mono:700italic" -oRoboto_Mono.css;
sh ./google-font-download "Fira Sans:100" "Fira Sans:100italic" "Fira Sans:200" "Fira Sans:200italic" "Fira Sans:300" "Fira Sans:300italic" "Fira Sans" "Fira Sans:italic" "Fira Sans:500" "Fira Sans:500italic" "Fira Sans:600" "Fira Sans:600italic" "Fira Sans:700" "Fira Sans:700italic" "Fira Sans:800" "Fira Sans:800italic" "Fira Sans:900" "Fira Sans:900italic" -oFira_Sans.css;
sh ./google-font-download "Merriweather Sans:300" "Merriweather Sans:300italic" "Merriweather Sans" "Merriweather Sans:italic" "Merriweather Sans:700" "Merriweather Sans:700italic" "Merriweather Sans:800" "Merriweather Sans:800italic" -oMerriweather_Sans.css;
sh ./google-font-download "Abril Fatface" -oAbril_Fatface.css;
sh ./google-font-download "Asap" "Asap:italic" "Asap:500" "Asap:500italic" "Asap:700" "Asap:700italic" -oAsap.css;
sh ./google-font-download "Varela Round" -oVarela_Round.css;
sh ./google-font-download "Exo 2:100" "Exo 2:100italic" "Exo 2:200" "Exo 2:200italic" "Exo 2:300" "Exo 2:300italic" "Exo 2" "Exo 2:italic" "Exo 2:500" "Exo 2:500italic" "Exo 2:600" "Exo 2:600italic" "Exo 2:700" "Exo 2:700italic" "Exo 2:800" "Exo 2:800italic" "Exo 2:900" "Exo 2:900italic" -oExo_2.css;
sh ./google-font-download "Quicksand:300" "Quicksand" "Quicksand:500" "Quicksand:700" -oQuicksand.css;
sh ./google-font-download "Abel" -oAbel.css;
sh ./google-font-download "Pacifico" -oPacifico.css;
sh ./google-font-download "Gloria Hallelujah" -oGloria_Hallelujah.css;
sh ./google-font-download "Karla" "Karla:italic" "Karla:700" "Karla:700italic" -oKarla.css;
sh ./google-font-download "Rubik:300" "Rubik:300italic" "Rubik" "Rubik:italic" "Rubik:500" "Rubik:500italic" "Rubik:700" "Rubik:700italic" "Rubik:900" "Rubik:900italic" -oRubik.css;
sh ./google-font-download "Ubuntu Condensed" -oUbuntu_Condensed.css;
sh ./google-font-download "Work Sans:100" "Work Sans:200" "Work Sans:300" "Work Sans" "Work Sans:500" "Work Sans:600" "Work Sans:700" "Work Sans:800" "Work Sans:900" -oWork_Sans.css;
sh ./google-font-download "Archivo Narrow" "Archivo Narrow:italic" "Archivo Narrow:700" "Archivo Narrow:700italic" -oArchivo_Narrow.css;
sh ./google-font-download "Signika:300" "Signika" "Signika:600" "Signika:700" -oSignika.css;
sh ./google-font-download "Questrial" -oQuestrial.css;
sh ./google-font-download "Cuprum" "Cuprum:italic" "Cuprum:700" "Cuprum:700italic" -oCuprum.css;
sh ./google-font-download "Shadows Into Light" -oShadows_Into_Light.css;
sh ./google-font-download "Play" "Play:700" -oPlay.css;
sh ./google-font-download "Dancing Script" "Dancing Script:700" -oDancing_Script.css;
sh ./google-font-download "Alegreya" "Alegreya:italic" "Alegreya:700" "Alegreya:700italic" "Alegreya:900" "Alegreya:900italic" -oAlegreya.css;
sh ./google-font-download "PT Sans Caption" "PT Sans Caption:700" -oPT_Sans_Caption.css;
sh ./google-font-download "Francois One" -oFrancois_One.css;
sh ./google-font-download "Exo:100" "Exo:100italic" "Exo:200" "Exo:200italic" "Exo:300" "Exo:300italic" "Exo" "Exo:italic" "Exo:500" "Exo:500italic" "Exo:600" "Exo:600italic" "Exo:700" "Exo:700italic" "Exo:800" "Exo:800italic" "Exo:900" "Exo:900italic" -oExo.css;
sh ./google-font-download "EB Garamond" -oEB_Garamond.css;
sh ./google-font-download "Acme" -oAcme.css;
sh ./google-font-download "Vollkorn" "Vollkorn:italic" "Vollkorn:700" "Vollkorn:700italic" -oVollkorn.css;
sh ./google-font-download "Maven Pro" "Maven Pro:500" "Maven Pro:700" "Maven Pro:900" -oMaven_Pro.css;
sh ./google-font-download "Amatic SC" "Amatic SC:700" -oAmatic_SC.css;
sh ./google-font-download "Pathway Gothic One" -oPathway_Gothic_One.css;
sh ./google-font-download "Archivo Black" -oArchivo_Black.css;
sh ./google-font-download "Orbitron" "Orbitron:500" "Orbitron:700" "Orbitron:900" -oOrbitron.css;
sh ./google-font-download "Source Code Pro:200" "Source Code Pro:300" "Source Code Pro" "Source Code Pro:500" "Source Code Pro:600" "Source Code Pro:700" "Source Code Pro:900" -oSource_Code_Pro.css;
sh ./google-font-download "Rokkitt:100" "Rokkitt:200" "Rokkitt:300" "Rokkitt" "Rokkitt:500" "Rokkitt:600" "Rokkitt:700" "Rokkitt:800" "Rokkitt:900" -oRokkitt.css;
sh ./google-font-download "Ropa Sans" "Ropa Sans:italic" -oRopa_Sans.css;
sh ./google-font-download "Libre Franklin:100" "Libre Franklin:100italic" "Libre Franklin:200" "Libre Franklin:200italic" "Libre Franklin:300" "Libre Franklin:300italic" "Libre Franklin" "Libre Franklin:italic" "Libre Franklin:500" "Libre Franklin:500italic" "Libre Franklin:600" "Libre Franklin:600italic" "Libre Franklin:700" "Libre Franklin:700italic" "Libre Franklin:800" "Libre Franklin:800italic" "Libre Franklin:900" "Libre Franklin:900italic" -oLibre_Franklin.css;
sh ./google-font-download "Crete Round" "Crete Round:italic" -oCrete_Round.css;
sh ./google-font-download "Istok Web" "Istok Web:italic" "Istok Web:700" "Istok Web:700italic" -oIstok_Web.css;
sh ./google-font-download "Patua One" -oPatua_One.css;
sh ./google-font-download "Architects Daughter" -oArchitects_Daughter.css;
sh ./google-font-download "Cinzel" "Cinzel:700" "Cinzel:900" -oCinzel.css;
sh ./google-font-download "Sanchez" "Sanchez:italic" -oSanchez.css;
sh ./google-font-download "Alegreya Sans:100" "Alegreya Sans:100italic" "Alegreya Sans:300" "Alegreya Sans:300italic" "Alegreya Sans" "Alegreya Sans:italic" "Alegreya Sans:500" "Alegreya Sans:500italic" "Alegreya Sans:700" "Alegreya Sans:700italic" "Alegreya Sans:800" "Alegreya Sans:800italic" "Alegreya Sans:900" "Alegreya Sans:900italic" -oAlegreya_Sans.css;
sh ./google-font-download "Source Serif Pro" "Source Serif Pro:600" "Source Serif Pro:700" -oSource_Serif_Pro.css;
sh ./google-font-download "Satisfy" -oSatisfy.css;
sh ./google-font-download "Josefin Slab:100" "Josefin Slab:100italic" "Josefin Slab:300" "Josefin Slab:300italic" "Josefin Slab" "Josefin Slab:italic" "Josefin Slab:600" "Josefin Slab:600italic" "Josefin Slab:700" "Josefin Slab:700italic" -oJosefin_Slab.css;
sh ./google-font-download "Comfortaa:300" "Comfortaa" "Comfortaa:700" -oComfortaa.css;
sh ./google-font-download "News Cycle" "News Cycle:700" -oNews_Cycle.css;
sh ./google-font-download "Russo One" -oRusso_One.css;
sh ./google-font-download "Lobster Two" "Lobster Two:italic" "Lobster Two:700" "Lobster Two:700italic" -oLobster_Two.css;
sh ./google-font-download "BenchNine:300" "BenchNine" "BenchNine:700" -oBenchNine.css;
sh ./google-font-download "Passion One" "Passion One:700" "Passion One:900" -oPassion_One.css;
sh ./google-font-download "Hammersmith One" -oHammersmith_One.css;
sh ./google-font-download "Old Standard TT" "Old Standard TT:italic" "Old Standard TT:700" -oOld_Standard_TT.css;
sh ./google-font-download "ABeeZee" "ABeeZee:italic" -oABeeZee.css;
sh ./google-font-download "Quattrocento Sans" "Quattrocento Sans:italic" "Quattrocento Sans:700" "Quattrocento Sans:700italic" -oQuattrocento_Sans.css;
sh ./google-font-download "Noticia Text" "Noticia Text:italic" "Noticia Text:700" "Noticia Text:700italic" -oNoticia_Text.css;
sh ./google-font-download "Cormorant Garamond:300" "Cormorant Garamond:300italic" "Cormorant Garamond" "Cormorant Garamond:italic" "Cormorant Garamond:500" "Cormorant Garamond:500italic" "Cormorant Garamond:600" "Cormorant Garamond:600italic" "Cormorant Garamond:700" "Cormorant Garamond:700italic" -oCormorant_Garamond.css;
sh ./google-font-download "Righteous" -oRighteous.css;
sh ./google-font-download "Gudea" "Gudea:italic" "Gudea:700" -oGudea.css;
sh ./google-font-download "Monda" "Monda:700" -oMonda.css;
sh ./google-font-download "Kaushan Script" -oKaushan_Script.css;
sh ./google-font-download "Rajdhani:300" "Rajdhani" "Rajdhani:500" "Rajdhani:600" "Rajdhani:700" -oRajdhani.css;
sh ./google-font-download "Quattrocento" "Quattrocento:700" -oQuattrocento.css;
sh ./google-font-download "Kanit:100" "Kanit:100italic" "Kanit:200" "Kanit:200italic" "Kanit:300" "Kanit:300italic" "Kanit" "Kanit:italic" "Kanit:500" "Kanit:500italic" "Kanit:600" "Kanit:600italic" "Kanit:700" "Kanit:700italic" "Kanit:800" "Kanit:800italic" "Kanit:900" "Kanit:900italic" -oKanit.css;
sh ./google-font-download "Yellowtail" -oYellowtail.css;
sh ./google-font-download "Poiret One" -oPoiret_One.css;
sh ./google-font-download "Courgette" -oCourgette.css;
sh ./google-font-download "Domine" "Domine:700" -oDomine.css;
sh ./google-font-download "Khand:300" "Khand" "Khand:500" "Khand:600" "Khand:700" -oKhand.css;
sh ./google-font-download "Cantarell" "Cantarell:italic" "Cantarell:700" "Cantarell:700italic" -oCantarell.css;
sh ./google-font-download "Economica" "Economica:italic" "Economica:700" "Economica:700italic" -oEconomica.css;
sh ./google-font-download "Permanent Marker" -oPermanent_Marker.css;
sh ./google-font-download "Pontano Sans" -oPontano_Sans.css;
sh ./google-font-download "Cabin Condensed" "Cabin Condensed:500" "Cabin Condensed:600" "Cabin Condensed:700" -oCabin_Condensed.css;
sh ./google-font-download "Philosopher" "Philosopher:italic" "Philosopher:700" "Philosopher:700italic" -oPhilosopher.css;
sh ./google-font-download "Tinos" "Tinos:italic" "Tinos:700" "Tinos:700italic" -oTinos.css;
sh ./google-font-download "Shrikhand" -oShrikhand.css;
sh ./google-font-download "Chewy" -oChewy.css;
sh ./google-font-download "Cookie" -oCookie.css;